project:
  type: website
  output-dir: docs

website:
  title: "Wilson de Oliveira Souza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tools.qmd
        text: tools
      - href: tips.qmd
        text: tips
      - href: techs.qmd
        text: techs
      - href: trends.qmd
        text: trends
      - href: tuts.qmd
        text: tuts

format:
  html:
    theme: lux
    css: styles.css
    toc: false



