project:
  type: website
  output-dir: docs

website:
  title: "Wilson de Oliveira Souza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tools.qmd
      - tips.qmd
      - techs.qmd
      - trends.qmd
      - tuts.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



