project:
  type: website
  output-dir: docs

website:
  title: "Wilson de Oliveira Souza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About.qmd
      - Tools.qmd
      - Tips.qmd
      - Texts.qmd
      - Techs.qmd
      - Trends.qmd
      - Tuts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



